/data/home/zzk/workspace/zzk/new_benchmark/projects/Rewrite/preprocess.py
/data/home/zzk/workspace/zzk/new_benchmark/projects/Rewrite/rewrite.py
/data/home/zzk/workspace/zzk/new_benchmark/projects/Rewrite/dataset.py
/data/home/zzk/workspace/zzk/new_benchmark/projects/Rewrite/utils.py
Not in virtualenv
cuDNN not found!
bazel not found
......................................................................................
Current library: scipy (v0.18.1)
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current library: numpy (v1.11.1)
Knowledge base: {'library': {'pandas': [('0.18.1', 'no', ['67923439'])]}, 'hardware': {}, 'programming_language': {'python': [('3.6', 'no', ['67923439']), ('3.5', 'yes', ['67923439'])]}, 'operating_system': {}, 'tool': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local numpy (v1.11.1) may not be compatible with python (v3.6) (4)
Recommand StackOverflow Posts: 
https://stackoverflow.com/questions/67923439
-----------------------------------END-------------------------------------------
++++++++++++++++++++++++++++API CHECK++++++++++++++++++++++++++++
......................................................................................
Current API: os.path.splitext
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {'python': [('3', 'no', ['541394'])]}, 'operating_system': {}, 'tool': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local os.path.splitext is not compatible with python (v3.6) (2)
Recommand StackOverflow Posts: 
https://stackoverflow.com/questions/541394
-----------------------------------END-------------------------------------------
......................................................................................
Current API: np.zeros
Knowledge base: {'library': {'numpy': [('3.95', 'yes', ['44866614'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: saver.restore
Knowledge base: {'library': {'tensorflow': [('0.12', 'no', ['41495299'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: os.path.exists
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {'python': [('3', 'yes', ['44661513']), ('2', 'no', ['44661513'])]}, 'operating_system': {}, 'tool': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local os.path.exists is not compatible with python (v3.6) (3)
-----------------------------------END-------------------------------------------
......................................................................................
Current API: np.arange
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {'python': [('3', 'yes', ['8097594']), ('2', 'yes', ['8097594']), ('6.65', 'yes', ['4618954'])]}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: os.path
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {'python': [('3.5', 'yes', ['37095733']), ('2.7', 'yes', ['3430395']), ('3', 'yes', ['3430395', '4119176', '44661513']), ('3.4', 'no', ['45223014', '51149057'])]}, 'operating_system': {}, 'tool': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local os.path is not compatible with python (v3.6) (3)
-----------------------------------END-------------------------------------------
......................................................................................
Current API: scipy.misc
Knowledge base: {'library': {'scipy': [('0.19', 'no', ['56743683'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: np.save
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {'python': [('3', 'yes', ['29707016'])]}, 'operating_system': {}, 'tool': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: np.save may not be compatible with python (v3.6) (1)
Recommand StackOverflow Posts: 
https://stackoverflow.com/questions/29707016
-----------------------------------END-------------------------------------------
......................................................................................
Current API: tf.nn.max_pool
Knowledge base: {'library': {}, 'hardware': {'cudnn': [('6', 'yes', ['47354833'])]}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: shutil.rmtree
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {'python': [('2', 'yes', ['48738480'])]}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: os.makedirs
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {'python': [('3.5', 'no', ['48987444'])]}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: tf.cond
Knowledge base: {'library': {'tensorflow': [('1', 'no', ['67691106']), ('1.4', 'yes', ['47769761'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: imageio.imread
Knowledge base: {'library': {'scipy': [('1', 'no', ['61263474'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: os.path.join
Knowledge base: {'library': {'tensorflow': [('8', 'no', ['6766266'])]}, 'hardware': {}, 'programming_language': {'python': [('9', 'no', ['47748008']), ('3', 'no', ['6766266']), ('3.4', 'no', ['2909998'])]}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: sys.setdefaultencoding
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {'python': [('2', 'yes', ['34378962'])]}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: sess.run
Knowledge base: {'library': {'tensorflow': [('1', 'yes', ['64942713'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: tf.nn.conv2d
Knowledge base: {'library': {}, 'hardware': {'cudnn': [('6', 'yes', ['47354833'])]}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: line.split
Knowledge base: {'library': {'tensorflow': [('8', 'no', ['57679193'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: np.array
Knowledge base: {'library': {'numpy': [('0.325', 'yes', ['67695754']), ('8.99849401', 'yes', ['46085625']), ('21.87729639', 'yes', ['46085625'])]}, 'hardware': {}, 'programming_language': {'python': [('3', 'no', ['3877247'])]}, 'operating_system': {}, 'tool': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local np.array is not compatible with python (v3.6) (2)
Recommand StackOverflow Posts: 
https://stackoverflow.com/questions/3877247
-----------------------------------END-------------------------------------------
......................................................................................
Current API: tf.placeholder
Knowledge base: {'library': {'tensorflow': [('2', 'no', ['60316058']), ('1.3', 'yes', ['47051723'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
