/data/home/zzk/workspace/zzk/Benchmark/projects/StyleGAN-Tensorflow/ops.py
/data/home/zzk/workspace/zzk/Benchmark/projects/StyleGAN-Tensorflow/main.py
/data/home/zzk/workspace/zzk/Benchmark/projects/StyleGAN-Tensorflow/utils.py
/data/home/zzk/workspace/zzk/Benchmark/projects/StyleGAN-Tensorflow/StyleGAN.py
Not in virtualenv
cuDNN not found!
bazel not found
numpy is not installed in local
pillow is not installed in local
......................................................................................
Current library: scipy (v1.2.0)
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
tqdm is not installed in local
opencv-python is not installed in local
tensorflow is not installed in local
++++++++++++++++++++++++++++API CHECK++++++++++++++++++++++++++++
......................................................................................
Current API: tf.nn.conv2d
Knowledge base: {'library': {}, 'hardware': {'cudnn': [('6', 'yes', ['47354833'])]}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: tf.constant
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: glob.glob
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {'python': [('3', 'yes', ['44661513', '48393588']), ('3.5', 'no', ['37173091', '44661513'])]}, 'operating_system': {}, 'tool': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local glob.glob is not compatible with python (v3.6) (3)
-----------------------------------END-------------------------------------------
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local glob.glob may not be compatible with python (v3.6) (4)
-----------------------------------END-------------------------------------------
......................................................................................
Current API: tf.assign
Knowledge base: {'library': {'keras': [('2.1', 'yes', ['47081613'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: tf.device
Knowledge base: {'library': {'tensorflow': [('3', 'yes', ['45544750'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: tf.clip_by_value
Knowledge base: {'library': {'tensorflow': [('1.4', 'yes', ['50026224'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: tf.tile
Knowledge base: {'library': {'tensorflow': [('1.12', 'no', ['59577132'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: np.sum
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {'python': [('4.5ms', 'yes', ['66886682'])]}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: tf.shape
Knowledge base: {'library': {'tensorflow': [('1.8', 'yes', ['50414384']), ('r1.1', 'yes', ['43883326'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: np.arange
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {'python': [('3', 'yes', ['8097594']), ('2', 'yes', ['8097594']), ('6.65', 'yes', ['4618954'])]}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: tf.where
Knowledge base: {'library': {'tensorflow': [('1', 'yes', ['38779798', '67691106'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: os.path
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {'python': [('3.5', 'yes', ['37095733']), ('2.7', 'yes', ['3430395']), ('3', 'yes', ['3430395', '4119176', '44661513']), ('3.4', 'no', ['45223014', '51149057'])]}, 'operating_system': {}, 'tool': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local os.path is not compatible with python (v3.6) (3)
-----------------------------------END-------------------------------------------
......................................................................................
Current API: tf.random_normal
Knowledge base: {'library': {'tensorflow': [('1', 'no', ['65740996'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: tf.nn.conv2d_transpose
Knowledge base: {'library': {'tensorflow': [('2', 'no', ['55199043'])]}, 'hardware': {'cudnn': [('6', 'yes', ['47354833'])]}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: tf.gradients
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {'python': [('2', 'no', ['43410170'])]}, 'operating_system': {}, 'tool': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local tf.gradients is not compatible with python (v3.6) (2)
Recommand StackOverflow Posts: 
https://stackoverflow.com/questions/43410170
-----------------------------------END-------------------------------------------
......................................................................................
Current API: tf.data
Knowledge base: {'library': {'tensorflow': [('1.5', 'yes', ['46732695'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: os.path.join
Knowledge base: {'library': {'tensorflow': [('8', 'no', ['6766266'])]}, 'hardware': {}, 'programming_language': {'python': [('9', 'no', ['47748008']), ('3', 'no', ['6766266']), ('3.4', 'no', ['2909998'])]}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: np.array
Knowledge base: {'library': {'numpy': [('0.325', 'yes', ['67695754']), ('8.99849401', 'yes', ['46085625']), ('21.87729639', 'yes', ['46085625'])]}, 'hardware': {}, 'programming_language': {'python': [('3', 'no', ['3877247'])]}, 'operating_system': {}, 'tool': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local np.array is not compatible with python (v3.6) (2)
Recommand StackOverflow Posts: 
https://stackoverflow.com/questions/3877247
-----------------------------------END-------------------------------------------
......................................................................................
Current API: os.makedirs
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {'python': [('3.5', 'no', ['48987444'])]}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: tf.cond
Knowledge base: {'library': {'tensorflow': [('1', 'no', ['67691106']), ('1.4', 'yes', ['47769761'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: tf.layers
Knowledge base: {'library': {'tensorflow': [('1', 'no', ['60430821']), ('0.3', 'no', ['59354744']), ('1.10', 'no', ['59354744']), ('1.14', 'no', ['59354744'])], 'keras': [('2', 'no', ['50048612'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: tf.get_variable
Knowledge base: {'library': {'tensorflow': [('1.4', 'yes', ['47189751'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: np.zeros
Knowledge base: {'library': {'numpy': [('3.95', 'yes', ['44866614'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: os.path.exists
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {'python': [('3', 'yes', ['44661513']), ('2', 'no', ['44661513'])]}, 'operating_system': {}, 'tool': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local os.path.exists is not compatible with python (v3.6) (3)
-----------------------------------END-------------------------------------------
......................................................................................
Current API: tensorflow.contrib
Knowledge base: {'library': {'tensorflow': [('2', 'no', ['55524156'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
