Not in virtualenv
cuDNN not found!
bazel not found
{'label': 'programming_language', 'name': 'python', 'version': '3.8', 'verdict': 'yes', 'post_id': ['68917678']}
{'label': 'programming_language', 'name': 'python', 'version': '3.9', 'verdict': 'yes', 'post_id': ['68917678']}
......................................................................................
Current library: numpy (v1.21.6)
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {'python': [('3.8', 'yes', ['68917678']), ('3.9', 'yes', ['68917678'])]}, 'operating_system': {}, 'tool': {}, 'database': {}, 'software': {}}
{'label': 'library', 'name': 'numpy', 'version': '1.15', 'verdict': 'yes', 'post_id': ['51909734', '52817582']}
unknown
......................................................................................
Current library: scipy (v1.2.0)
Knowledge base: {'library': {'numpy': [('1.15', 'yes', ['51909734', '52817582'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}, 'database': {}, 'software': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local scipy (v1.2.0) may not be compatible with numpy (v1.21.6) (1)
Recommend StackOverflow Posts: 
https://stackoverflow.com/questions/51909734
https://stackoverflow.com/questions/52817582
-----------------------------------END-------------------------------------------
opencv-python is not installed in local
unknown
unknown
{'label': 'operating_system', 'name': 'ubuntu', 'version': '16.0.4', 'verdict': 'yes', 'post_id': ['59108370']}
unknown
unknown
{'label': 'library', 'name': 'tfds', 'version': '4', 'verdict': 'no', 'post_id': ['65795196']}
{'label': 'hardware', 'name': 'cuda', 'version': '11', 'verdict': 'no', 'post_id': ['65619544']}
{'label': 'hardware', 'name': 'cuda', 'version': '10.1', 'verdict': 'no', 'post_id': ['65432123']}
unknown
......................................................................................
Current library: tensorflow (v1.15.4)
Knowledge base: {'library': {'tfds': [('4', 'no', ['65795196'])]}, 'hardware': {'cuda': [('11', 'no', ['65619544']), ('10.1', 'no', ['65432123'])]}, 'programming_language': {}, 'operating_system': {'ubuntu': [('16.0.4', 'yes', ['59108370'])]}, 'tool': {}, 'database': {}, 'software': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local tensorflow (v1.15.4) is not compatible with cuda (v11.7) (0)
-----------------------------------END-------------------------------------------
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local tensorflow (v1.15.4) may not be compatible with ubuntu (v18.04) (1)
Recommend StackOverflow Posts: 
https://stackoverflow.com/questions/59108370
-----------------------------------END-------------------------------------------
