/data/home/zzk/workspace/zzk/Benchmark/projects/gcn/setup.py
/data/home/zzk/workspace/zzk/Benchmark/projects/gcn/gcn/inits.py
/data/home/zzk/workspace/zzk/Benchmark/projects/gcn/gcn/__init__.py
/data/home/zzk/workspace/zzk/Benchmark/projects/gcn/gcn/metrics.py
/data/home/zzk/workspace/zzk/Benchmark/projects/gcn/gcn/train.py
/data/home/zzk/workspace/zzk/Benchmark/projects/gcn/gcn/models.py
/data/home/zzk/workspace/zzk/Benchmark/projects/gcn/gcn/utils.py
/data/home/zzk/workspace/zzk/Benchmark/projects/gcn/gcn/layers.py
Not in virtualenv
cuDNN not found!
bazel not found
......................................................................................
Current library: scipy (v1.1.0)
Knowledge base: {'library': {'numpy': [('1.8.1rc1', 'no', ['45703036'])]}, 'hardware': {}, 'programming_language': {'python': [('3.6', 'no', ['59269352']), ('3.5.6', 'yes', ['59269352'])]}, 'operating_system': {}, 'tool': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local scipy (v1.1.0) may not be compatible with python (v3.6) (4)
Recommand StackOverflow Posts: 
https://stackoverflow.com/questions/59269352
-----------------------------------END-------------------------------------------
......................................................................................
Current library: numpy (v1.15.4)
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {'python': [('3.7.1', 'yes', ['53499006'])]}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current library: tensorflow (v1.15.4)
Knowledge base: {'library': {'tfds': [('2.1', 'yes', ['68263473']), ('3.2.1', 'yes', ['65795196']), ('4', 'no', ['65795196'])], 'keras': [('2.3.1', 'yes', ['67171045'])]}, 'hardware': {'cuda': [('110', 'yes', ['65619544']), ('10', 'yes', ['59982494', '67734574', '60077642'])]}, 'programming_language': {'python': [('3.7', 'yes', ['61594971']), ('3.8', 'no', ['61594971'])]}, 'operating_system': {'ubuntu': [('16.0.4', 'yes', ['59108370'])]}, 'tool': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local tensorflow (v1.15.4) is not compatible with cuda (v11.2) (0)
-----------------------------------END-------------------------------------------
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local tensorflow (v1.15.4) may not be compatible with python (v3.6) (4)
Recommand StackOverflow Posts: 
https://stackoverflow.com/questions/61594971
-----------------------------------END-------------------------------------------
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local tensorflow (v1.15.4) may not be compatible with ubuntu (v18.04.1) (1)
Recommand StackOverflow Posts: 
https://stackoverflow.com/questions/59108370
-----------------------------------END-------------------------------------------
++++++++++++++++++++++++++++API CHECK++++++++++++++++++++++++++++
......................................................................................
Current API: np.array
Knowledge base: {'library': {'numpy': [('0.325', 'yes', ['67695754']), ('8.99849401', 'yes', ['46085625']), ('21.87729639', 'yes', ['46085625'])]}, 'hardware': {}, 'programming_language': {'python': [('3', 'no', ['3877247'])]}, 'operating_system': {}, 'tool': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local np.array is not compatible with python (v3.6) (2)
Recommand StackOverflow Posts: 
https://stackoverflow.com/questions/3877247
-----------------------------------END-------------------------------------------
......................................................................................
Current API: scipy.sparse
Knowledge base: {'library': {'scipy': [('2', 'yes', ['65017153'])]}, 'hardware': {}, 'programming_language': {'python': [('2', 'yes', ['42625707'])]}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: tf.zeros
Knowledge base: {'library': {'tensorflow': [('2', 'yes', ['59585408']), ('1.5', 'yes', ['59585408'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: np.zeros
Knowledge base: {'library': {'numpy': [('3.95', 'yes', ['44866614'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: saver.restore
Knowledge base: {'library': {'tensorflow': [('0.12', 'no', ['41495299'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: tf.placeholder
Knowledge base: {'library': {'tensorflow': [('2', 'no', ['60316058']), ('1.3', 'yes', ['47051723'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: sess.run
Knowledge base: {'library': {'tensorflow': [('1', 'yes', ['64942713'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current API: tf.equal
Knowledge base: {'library': {'tensorflow': [('1.8', 'yes', ['50414384'])]}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
