/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/config_mri.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/config.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/util.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/dataset_tool_mri.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/dataset_tool_tf.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/dataset.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/train.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/validation.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/train_mri.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/network.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/download_kodak.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/dnnlib/util.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/dnnlib/__init__.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/dnnlib/submission/__init__.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/dnnlib/submission/submit.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/dnnlib/submission/run_context.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/dnnlib/submission/_internal/run.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/dnnlib/tflib/autosummary.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/dnnlib/tflib/__init__.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/dnnlib/tflib/network.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/dnnlib/tflib/optimizer.py
/data/home/zzk/workspace/zzk/Benchmark/projects/noise2noise/dnnlib/tflib/tfutil.py
Not in virtualenv
cuDNN not found!
bazel not found
......................................................................................
Current library: scipy (v1.1.0)
Knowledge base: {'library': {'numpy': [('1.8.1rc1', 'no', ['45703036'])]}, 'hardware': {}, 'programming_language': {'python': [('3.6', 'no', ['59269352']), ('3.5.6', 'yes', ['59269352'])]}, 'operating_system': {}, 'tool': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local scipy (v1.1.0) is not compatible with python (v3.6) (3)
Recommand StackOverflow Posts: 
https://stackoverflow.com/questions/59269352
-----------------------------------END-------------------------------------------
tensorflow is not installed in local
