/data/home/zzk/workspace/zzk/new_benchmark/projects/Rewrite/preprocess.py
/data/home/zzk/workspace/zzk/new_benchmark/projects/Rewrite/rewrite.py
/data/home/zzk/workspace/zzk/new_benchmark/projects/Rewrite/dataset.py
/data/home/zzk/workspace/zzk/new_benchmark/projects/Rewrite/utils.py
Not in virtualenv
cuDNN not found!
bazel not found
......................................................................................
Current library: scipy (v0.18.1)
Knowledge base: {'library': {}, 'hardware': {}, 'programming_language': {}, 'operating_system': {}, 'tool': {}}
......................................................................................
Current library: numpy (v1.11.1)
Knowledge base: {'library': {'pandas': [('0.18.1', 'no', ['67923439'])]}, 'hardware': {}, 'programming_language': {'python': [('3.6', 'no', ['67923439']), ('3.5', 'yes', ['67923439'])]}, 'operating_system': {}, 'tool': {}}
--------------------------------DC ISSUE-----------------------------------------
ERROR: Local numpy (v1.11.1) is not compatible with python (v3.6) (3)
Recommand StackOverflow Posts: 
https://stackoverflow.com/questions/67923439
-----------------------------------END-------------------------------------------
